








//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace MD.DataModels
{
    /// <summary>
    /// Database       : modulo
    /// Data Source    : LOREDANA\DEVLM
    /// Server Version : 15.00.2080
    /// </summary>
    public partial class ModuloDB : LinqToDB.Data.DataConnection
    {
        public ITable<Module> Modules { get { return this.GetTable<Module>(); } }
        public ITable<ModuleToRole> ModuleToRoles { get { return this.GetTable<ModuleToRole>(); } }
        public ITable<Role> Roles { get { return this.GetTable<Role>(); } }
        public ITable<User> Users { get { return this.GetTable<User>(); } }
        public ITable<UserToRole> UserToRoles { get { return this.GetTable<UserToRole>(); } }

        public ModuloDB()
        {
            InitDataContext();
            InitMappingSchema();
        }

        public ModuloDB(string configuration)
            : base(configuration)
        {
            InitDataContext();
            InitMappingSchema();
        }

        public ModuloDB(DataOptions options)
            : base(options)
        {
            InitDataContext();
            InitMappingSchema();
        }

        partial void InitDataContext();
        partial void InitMappingSchema();
    }

    [Table(Schema = "dbo", Name = "Modules")]
    public partial class Module
    {
        [Column("id"), PrimaryKey, NotNull] public string Id { get; set; } // varchar(50)
        [Column("needsauthentication"), NotNull] public bool Needsauthentication { get; set; } // bit
        [Column("title"), NotNull] public string Title { get; set; } // nvarchar(150)
        [Column("name"), Nullable] public string Name { get; set; } // varchar(50)
        [Column("description"), Nullable] public string Description { get; set; } // nvarchar(500)
        [Column("modulegroup"), NotNull] public string Modulegroup { get; set; } // varchar(50)
    }

    [Table(Schema = "dbo", Name = "ModuleToRoles")]
    public partial class ModuleToRole
    {
        [Column("module_id"), PrimaryKey(1), NotNull] public string ModuleId { get; set; } // varchar(50)
        [Column("role_id"), PrimaryKey(2), NotNull] public int RoleId { get; set; } // int
    }

    [Table(Schema = "dbo", Name = "Role")]
    public partial class Role
    {
        [PrimaryKey, Identity] public int Id { get; set; } // int
        [Column, NotNull] public string RoleName { get; set; } // varchar(50)
    }

    [Table(Schema = "dbo", Name = "User")]
    public partial class User
    {
        [PrimaryKey, Identity] public int UserID { get; set; } // int
        [Column, NotNull] public string UserName { get; set; } // nvarchar(40)
        [Column, NotNull] public byte[] PasswordHash { get; set; } // binary(64)
        [Column, Nullable] public string FirstName { get; set; } // nvarchar(40)
        [Column, Nullable] public string LastName { get; set; } // nvarchar(40)
        [Column, Nullable] public string Email { get; set; } // varchar(1000)
        [Column, Nullable] public Guid? Salt { get; set; } // uniqueidentifier
        [Column, Nullable] public DateTime? EntryDate { get; set; } // datetime
        [Column, Nullable] public DateTime? ModifiedDate { get; set; } // datetime
    }

    [Table(Schema = "dbo", Name = "UserToRoles")]
    public partial class UserToRole
    {
        [PrimaryKey(1), NotNull] public int RoleId { get; set; } // int
        [PrimaryKey(2), NotNull] public int UserId { get; set; } // int
    }

    public static partial class TableExtensions
    {
        public static Module Find(this ITable<Module> table, string Id)
        {
            return table.FirstOrDefault(t =>
                t.Id == Id);
        }

        public static ModuleToRole Find(this ITable<ModuleToRole> table, string ModuleId, int RoleId)
        {
            return table.FirstOrDefault(t =>
                t.ModuleId == ModuleId &&
                t.RoleId == RoleId);
        }

        public static Role Find(this ITable<Role> table, int Id)
        {
            return table.FirstOrDefault(t =>
                t.Id == Id);
        }

        public static User Find(this ITable<User> table, int UserID)
        {
            return table.FirstOrDefault(t =>
                t.UserID == UserID);
        }

        public static UserToRole Find(this ITable<UserToRole> table, int RoleId, int UserId)
        {
            return table.FirstOrDefault(t =>
                t.RoleId == RoleId &&
                t.UserId == UserId);
        }
    }
}

#pragma warning restore 1591
